apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cerebro
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://stakater.github.io/stakater-charts
    chart: cerebro
    targetRevision: 0.5.1
    # helm:
    #   values: |
    #     elasticsearchHosts: "http://elasticsearch-logging-master:9200"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging