apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 7.10.2
    helm:
      values: |
        elasticsearchHosts: "http://elasticsearch-logging-master:9200"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging