apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuard
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/keefeere/Lection17ArgoCD.git
    targetRevision: HEAD
    path: helm-charts/kuard
    helm:
      values: |
        fullnameOverride: "kuard"
        env:
          ENV: "demo"
        image:
          tag: "1"
        ingress:
          enabled: true
          hosts:
            - host: kuard.keefeere.tk
        resources:
           requests:
             cpu: 10m
             memory: 128Mi
           limits:
             memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: default


#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: kuard-deployment
#  namespace: demo
#  labels:
#    app: kuard
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: kuard
#  template:
#    metadata:
#      labels:
#        app: kuard
#    spec:
#      containers:
#        - image: gcr.io/kuar-demo/kuard-amd64:1
#          name: kuard
#          ports:
#            - containerPort: 8080
#              name: http
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: kuard-service
#  namespace: demo
#spec:
#  selector:
#    app: kuard
#  ports:
#    - port: 80
#      targetPort: 8080
#---
#apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
#  name: kuard
#  namespace: demo
#  labels:
#    app.kubernetes.io/component: server
#spec:
#  rules:
#    - host: kuard.devopsua.tk
#      http:
#        paths:
#          - backend:
#              serviceName: kuard-service
#              servicePort: 80
#            path: /
#            pathType: ImplementationSpecific